# question_data = [
#     {"text": "A slug's blood is green.", "answer": "True"},
#     {"text": "The loudest animal is the African Elephant.", "answer": "False"},
#     {"text": "Approximately one quarter of human bones are in the feet.", "answer": "True"},
#     {"text": "The total surface area of a human lungs is the size of a football pitch.", "answer": "True"},
#     {"text": "In West Virginia, USA, if you accidentally hit an animal with your car, "
#              "you are free to take it home to eat.", "answer": "True"},
#     {"text": "In London, UK, if you happen to die in the House of Parliament, "
#              "you are entitled to a state funeral.", "answer": "False"},
#     {"text": "It is illegal to pee in the Ocean in Portugal.", "answer": "True"},
#     {"text": "You can lead a cow down stairs but not up stairs.", "answer": "False"},
#     {"text": "Google was originally called 'Backrub'.", "answer": "True"},
#     {"text": "Buzz Aldrin's mother's maiden name was 'Moon'.", "answer": "True"},
#     {"text": "No piece of square dry paper can be folded in half more than 7 times.", "answer": "False"},
#     {"text": "A few ounces of chocolate can to kill a small dog.", "answer": "True"}
# ]


# question_data = [
#     {"category": "Entertainment: Video Games",
#      "type": "boolean", "difficulty": "easy",
#      "question": "The main character in the &quot;Half-Life&quot; franchise is named Morgan Freeman.",
#      "correct_answer": "False",
#      "incorrect_answers": ["True"]},
#     {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
#      "question": "The Indie Game Development Studio Cing, developers of Hotel Dusk and Last Window, went bankrupt on March 1st, 2010.",
#      "correct_answer": "True", "incorrect_answers": ["False"]},
#     {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
#      "question": "The Mann Co. Store from Team Fortress 2 has the slogan &quot;We hire mercenaries and get in fights&quot;.",
#      "correct_answer": "False", "incorrect_answers": ["True"]},
#     {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
#      "question": "In &quot;Mario Kart 64&quot;, Waluigi is a playable character.",
#      "correct_answer": "False",
#      "incorrect_answers": ["True"]},
#     {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
#      "question": "Faust is a playable character in &quot;Guilty Gear Xrd Revelator&quot;.",
#      "correct_answer": "True", "incorrect_answers": ["False"]},
#     {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
#      "question": "There are 6 legendary cards in &quot;Clash Royale&quot;.", "correct_answer": "False",
#      "incorrect_answers": ["True"]},
#     {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
#      "question": "&quot;Half-Life 2&quot; runs on the Source Engine.",
#      "correct_answer": "True", "incorrect_answers": ["False"]},
#     {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
#      "question": "Donkey Kong was originally set to be a Popeye arcade game.",
#      "correct_answer": "True",
#      "incorrect_answers": ["False"]},
#     {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
#      "question": "Pac-Man was invented by the designer Toru Iwatani while he was eating pizza.",
#      "correct_answer": "True", "incorrect_answers": ["False"]},
#     {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
#      "question": "In &quot;Super Mario Bros.&quot;, the clouds and bushes have the same artwork and are just different colors.",
#      "correct_answer": "True", "incorrect_answers": ["False"]},
#     {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
#      "question": "Niko Bellic is the protagonist of Grand Theft Auto IV.", "correct_answer": "True",
#      "incorrect_answers": ["False"]},
#     {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
#      "question": "Tetris is the #1 best-selling video game of all-time.", "correct_answer": "False",
#      "incorrect_answers": ["True"]},
#     {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
#      "question": "Deus Ex (2000) does not feature the World Trade Center because it was destroyed by terrorist attacks according to the game&#039;s plot.",
#      "correct_answer": "True", "incorrect_answers": ["False"]},
#     {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
#      "question": "Gordon Freeman, the protagonist of &quot;Half-Life&quot;, is said to have once had a ponytail.",
#      "correct_answer": "True", "incorrect_answers": ["False"]},
#     {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
#      "question": "The PlayStation was originally a joint project between Sega and Sony that was a Sega Genesis with a disc drive.",
#      "correct_answer": "False", "incorrect_answers": ["True"]},
#     {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
#      "question": "The 2005 video game &quot;Call of Duty 2: Big Red One&quot; is not available on PC.",
#      "correct_answer": "True", "incorrect_answers": ["False"]},
#     {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
#      "question": "The main playable character of the 2015 RPG &quot;Undertale&quot; is a monster.",
#      "correct_answer": "False", "incorrect_answers": ["True"]},
#     {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
#      "question": "Rebecca Chambers does not appear in any Resident Evil except for the original Resident Evil and the Gamecube remake.",
#      "correct_answer": "False", "incorrect_answers": ["True"]},
#     {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
#      "question": "In the game &quot;Subnautica&quot;, a &quot;Spadefish&quot; will attack you.",
#      "correct_answer": "False", "incorrect_answers": ["True"]},
#     {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
#      "question": "In Terraria, you can craft the Cell Phone pre-hardmode.", "correct_answer": "True",
#      "incorrect_answers": ["False"]},
#     {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
#      "question": "In Pok&eacute;mon, Bulbasaur is the only starter pokemon that is a Grass\/Poison type.",
#      "correct_answer": "True", "incorrect_answers": ["False"]},
#     {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
#      "question": "In &quot;Undertale&quot;, the main character of the game is Sans.",
#      "correct_answer": "False",
#      "incorrect_answers": ["True"]},
#     {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
#      "question": "Watch_Dogs 2 is a prequel.", "correct_answer": "False",
#      "incorrect_answers": ["True"]},
#     {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
#      "question": "In Heroes of the Storm, the Cursed Hollow map gimmick requires players to kill the undead to curse the enemy team.",
#      "correct_answer": "False", "incorrect_answers": ["True"]},
#     {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
#      "question": "Several characters in &quot;Super Mario 64&quot; blink their eyes, including Mario himself.",
#      "correct_answer": "True", "incorrect_answers": ["False"]},
#     {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
#      "question": "Activision created Battlefield 1.", "correct_answer": "False",
#      "incorrect_answers": ["True"]},
#     {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
#      "question": "&quot;Sonic the Hedgehog 2&quot; originally was going to have a time travel system.",
#      "correct_answer": "True", "incorrect_answers": ["False"]},
#     {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
#      "question": "In &quot;Need for Speed: Porsche Unleashed&quot;, the player can only drive cars manufactured by Porsche.",
#      "correct_answer": "True", "incorrect_answers": ["False"]},
#     {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
#      "question": "In Until Dawn, both characters Sam and Mike cannot be killed under any means until the final chapter of the game.",
#      "correct_answer": "True", "incorrect_answers": ["False"]},
#     {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
#      "question": "The shotgun appears in every numbered Resident Evil game.", "correct_answer": "True",
#      "incorrect_answers": ["False"]}]






